# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 634)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 811, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_1)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(410, 10, 391, 351))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.PlatformLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.PlatformLayout.setContentsMargins(11, 0, 11, 0)
        self.PlatformLayout.setSpacing(0)
        self.PlatformLayout.setObjectName("PlatformLayout")
        self.rert = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.rert.setObjectName("rert")
        self.PlatformLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rert)
        self.rertEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.rertEdit.setObjectName("rertEdit")
        self.PlatformLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rertEdit)
        self.hert = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.hert.setObjectName("hert")
        self.PlatformLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.hert)
        self.hertEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.hertEdit.setObjectName("hertEdit")
        self.PlatformLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hertEdit)
        self.moin = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.moin.setObjectName("moin")
        self.PlatformLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.moin)
        self.moinEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.moinEdit.setObjectName("moinEdit")
        self.PlatformLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.moinEdit)
        self.rece = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.rece.setObjectName("rece")
        self.PlatformLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rece)
        self.receEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.receEdit.setObjectName("receEdit")
        self.PlatformLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.receEdit)
        self.sder = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.sder.setObjectName("sder")
        self.PlatformLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sder)
        self.sderEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.sderEdit.setObjectName("sderEdit")
        self.PlatformLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sderEdit)
        self.vaon = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.vaon.setObjectName("vaon")
        self.PlatformLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.vaon)
        self.vaonEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.vaonEdit.setObjectName("vaonEdit")
        self.PlatformLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.vaonEdit)
        self.nues = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nues.setObjectName("nues")
        self.PlatformLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.nues)
        self.nuesEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nuesEdit.setObjectName("nuesEdit")
        self.PlatformLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nuesEdit)
        self.slme = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.slme.setObjectName("slme")
        self.PlatformLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.slme)
        self.slmeEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.slmeEdit.setObjectName("slmeEdit")
        self.PlatformLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.slmeEdit)
        self.slth = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.slth.setObjectName("slth")
        self.PlatformLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.slth)
        self.slthEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.slthEdit.setObjectName("slthEdit")
        self.PlatformLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.slthEdit)
        self.vccc = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.vccc.setObjectName("vccc")
        self.PlatformLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.vccc)
        self.vcccEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.vcccEdit.setObjectName("vcccEdit")
        self.PlatformLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.vcccEdit)
        self.thrt = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.thrt.setObjectName("thrt")
        self.PlatformLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.thrt)
        self.thrtEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.thrtEdit.setObjectName("thrtEdit")
        self.PlatformLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.thrtEdit)
        self.sepe = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.sepe.setObjectName("sepe")
        self.PlatformLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.sepe)
        self.sepeEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.sepeEdit.setObjectName("sepeEdit")
        self.PlatformLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.sepeEdit)
        self.elrt = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.elrt.setObjectName("elrt")
        self.PlatformLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.elrt)
        self.elrtEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.elrtEdit.setObjectName("elrtEdit")
        self.PlatformLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.elrtEdit)
        self.tyor = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.tyor.setObjectName("tyor")
        self.PlatformLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.tyor)
        self.tyorEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.tyorEdit.setObjectName("tyorEdit")
        self.PlatformLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.tyorEdit)
        self.reme = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.reme.setObjectName("reme")
        self.PlatformLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.reme)
        self.remeEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.remeEdit.setObjectName("remeEdit")
        self.PlatformLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.remeEdit)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 360, 391, 336))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.RegresionWidget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.RegresionWidget.setObjectName("RegresionWidget")
        self.formLayout = QtWidgets.QFormLayout(self.RegresionWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.tecy = QtWidgets.QLabel(self.RegresionWidget)
        self.tecy.setObjectName("tecy")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tecy)
        self.heor = QtWidgets.QLabel(self.RegresionWidget)
        self.heor.setObjectName("heor")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.heor)
        self.tecyEdit = QtWidgets.QLineEdit(self.RegresionWidget)
        self.tecyEdit.setObjectName("tecyEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tecyEdit)
        self.heorEdit = QtWidgets.QLineEdit(self.RegresionWidget)
        self.heorEdit.setObjectName("heorEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.heorEdit)
        self.gridLayout_5.addWidget(self.RegresionWidget, 0, 0, 1, 1)
        self.MartinelliWidget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.MartinelliWidget.setObjectName("MartinelliWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.MartinelliWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.exio = QtWidgets.QLabel(self.MartinelliWidget)
        self.exio.setObjectName("exio")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.exio)
        self.teur = QtWidgets.QLabel(self.MartinelliWidget)
        self.teur.setObjectName("teur")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.teur)
        self.mali = QtWidgets.QLabel(self.MartinelliWidget)
        self.mali.setObjectName("mali")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mali)
        self.mili = QtWidgets.QLabel(self.MartinelliWidget)
        self.mili.setObjectName("mili")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mili)
        self.exioEdit = QtWidgets.QLineEdit(self.MartinelliWidget)
        self.exioEdit.setObjectName("exioEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.exioEdit)
        self.teurEdit = QtWidgets.QLineEdit(self.MartinelliWidget)
        self.teurEdit.setObjectName("teurEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.teurEdit)
        self.maliEdit = QtWidgets.QLineEdit(self.MartinelliWidget)
        self.maliEdit.setObjectName("maliEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maliEdit)
        self.miliEdit = QtWidgets.QLineEdit(self.MartinelliWidget)
        self.miliEdit.setObjectName("miliEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.miliEdit)
        self.gridLayout_5.addWidget(self.MartinelliWidget, 1, 0, 1, 1)
        self.PIDWidget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.PIDWidget.setObjectName("PIDWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.PIDWidget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.peod = QtWidgets.QLabel(self.PIDWidget)
        self.peod.setObjectName("peod")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.peod)
        self.upax = QtWidgets.QLabel(self.PIDWidget)
        self.upax.setObjectName("upax")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.upax)
        self.upin = QtWidgets.QLabel(self.PIDWidget)
        self.upin.setObjectName("upin")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.upin)
        self.loax = QtWidgets.QLabel(self.PIDWidget)
        self.loax.setObjectName("loax")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.loax)
        self.loin = QtWidgets.QLabel(self.PIDWidget)
        self.loin.setObjectName("loin")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.loin)
        self.alha = QtWidgets.QLabel(self.PIDWidget)
        self.alha.setObjectName("alha")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.alha)
        self.maue = QtWidgets.QLabel(self.PIDWidget)
        self.maue.setObjectName("maue")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.maue)
        self.miue = QtWidgets.QLabel(self.PIDWidget)
        self.miue.setEnabled(True)
        self.miue.setObjectName("miue")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.miue)
        self.peodEdit = QtWidgets.QLineEdit(self.PIDWidget)
        self.peodEdit.setObjectName("peodEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.peodEdit)
        self.upaxEdit = QtWidgets.QLineEdit(self.PIDWidget)
        self.upaxEdit.setObjectName("upaxEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.upaxEdit)
        self.upinEdit = QtWidgets.QLineEdit(self.PIDWidget)
        self.upinEdit.setObjectName("upinEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.upinEdit)
        self.loaxEdit = QtWidgets.QLineEdit(self.PIDWidget)
        self.loaxEdit.setObjectName("loaxEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.loaxEdit)
        self.loinEdit = QtWidgets.QLineEdit(self.PIDWidget)
        self.loinEdit.setObjectName("loinEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.loinEdit)
        self.alhaEdit = QtWidgets.QLineEdit(self.PIDWidget)
        self.alhaEdit.setObjectName("alhaEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.alhaEdit)
        self.maueEdit = QtWidgets.QLineEdit(self.PIDWidget)
        self.maueEdit.setObjectName("maueEdit")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.maueEdit)
        self.miueEdit = QtWidgets.QLineEdit(self.PIDWidget)
        self.miueEdit.setObjectName("miueEdit")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.miueEdit)
        self.gridLayout_5.addWidget(self.PIDWidget, 2, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(410, 380, 391, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.ButtonsLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.ButtonsLayout.setContentsMargins(10, 11, 10, 11)
        self.ButtonsLayout.setSpacing(10)
        self.ButtonsLayout.setObjectName("ButtonsLayout")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.ButtonsLayout.addWidget(self.startButton)
        self.LoadButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.LoadButton.setObjectName("LoadButton")
        self.ButtonsLayout.addWidget(self.LoadButton)
        self.SaveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SaveButton.setObjectName("SaveButton")
        self.ButtonsLayout.addWidget(self.SaveButton)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_1)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 391, 351))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.PuroLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget_4)
        self.PuroLayout.setContentsMargins(11, 11, 11, 11)
        self.PuroLayout.setSpacing(0)
        self.PuroLayout.setObjectName("PuroLayout")
        self.Modulation = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.Modulation.setObjectName("Modulation")
        self.Modulation.addItem("")
        self.Modulation.addItem("")
        self.Modulation.addItem("")
        self.Modulation.addItem("")
        self.PuroLayout.addWidget(self.Modulation)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.nuts = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.nuts.setEnabled(True)
        self.nuts.setObjectName("nuts")
        self.verticalLayout_6.addWidget(self.nuts)
        self.suon = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.suon.setObjectName("suon")
        self.verticalLayout_6.addWidget(self.suon)
        self.ales = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.ales.setObjectName("ales")
        self.verticalLayout_6.addWidget(self.ales)
        self.duon = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.duon.setObjectName("duon")
        self.verticalLayout_6.addWidget(self.duon)
        self.ines = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.ines.setObjectName("ines")
        self.verticalLayout_6.addWidget(self.ines)
        self.tius = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.tius.setObjectName("tius")
        self.verticalLayout_6.addWidget(self.tius)
        self.nale = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.nale.setObjectName("nale")
        self.verticalLayout_6.addWidget(self.nale)
        self.naer = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.naer.setObjectName("naer")
        self.verticalLayout_6.addWidget(self.naer)
        self.slep = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.slep.setObjectName("slep")
        self.verticalLayout_6.addWidget(self.slep)
        self.vees = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.vees.setObjectName("vees")
        self.verticalLayout_6.addWidget(self.vees)
        self.exon = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.exon.setObjectName("exon")
        self.verticalLayout_6.addWidget(self.exon)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.nutsEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.nutsEdit.setObjectName("nutsEdit")
        self.verticalLayout_7.addWidget(self.nutsEdit)
        self.suonEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.suonEdit.setObjectName("suonEdit")
        self.verticalLayout_7.addWidget(self.suonEdit)
        self.alesEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.alesEdit.setObjectName("alesEdit")
        self.verticalLayout_7.addWidget(self.alesEdit)
        self.duonEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.duonEdit.setObjectName("duonEdit")
        self.verticalLayout_7.addWidget(self.duonEdit)
        self.inesEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.inesEdit.setObjectName("inesEdit")
        self.verticalLayout_7.addWidget(self.inesEdit)
        self.tiusEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.tiusEdit.setObjectName("tiusEdit")
        self.verticalLayout_7.addWidget(self.tiusEdit)
        self.naleEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.naleEdit.setObjectName("naleEdit")
        self.verticalLayout_7.addWidget(self.naleEdit)
        self.naerEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.naerEdit.setObjectName("naerEdit")
        self.verticalLayout_7.addWidget(self.naerEdit)
        self.slepEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.slepEdit.setObjectName("slepEdit")
        self.verticalLayout_7.addWidget(self.slepEdit)
        self.veesEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.veesEdit.setObjectName("veesEdit")
        self.verticalLayout_7.addWidget(self.veesEdit)
        self.exonEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.exonEdit.setObjectName("exonEdit")
        self.verticalLayout_7.addWidget(self.exonEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.PuroLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 0, 82, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 832, 20))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rert.setText(_translate("MainWindow", "Puerto de lectura"))
        self.hert.setText(_translate("MainWindow", "Puerto de calentamiento"))
        self.moin.setText(_translate("MainWindow", "Pin del motor"))
        self.rece.setText(_translate("MainWindow", "Resistencia"))
        self.sder.setText(_translate("MainWindow", "Tarjeta SD"))
        self.vaon.setText(_translate("MainWindow", "Posición de las vávulas"))
        self.nues.setText(_translate("MainWindow", "Número muestras"))
        self.slme.setText(_translate("MainWindow", "Frecuencia muestras(segundos)"))
        self.slth.setText(_translate("MainWindow", "Frecuencia muestras TyH(secs.)"))
        self.vccc.setText(_translate("MainWindow", "VCC"))
        self.thrt.setText(_translate("MainWindow", "Puerto lectura TyH"))
        self.sepe.setText(_translate("MainWindow", "Modelo sensor TyH"))
        self.elrt.setText(_translate("MainWindow", "Puertos electroválvulas"))
        self.tyor.setText(_translate("MainWindow", "Tipo sensor"))
        self.reme.setText(_translate("MainWindow", "Tiempo lectura"))
        self.tecy.setText(_translate("MainWindow", "Tendencia"))
        self.heor.setText(_translate("MainWindow", "Temperatura sensor"))
        self.exio.setText(_translate("MainWindow", "Modo ejecucion"))
        self.teur.setText(_translate("MainWindow", "Variación temperatura"))
        self.mali.setText(_translate("MainWindow", "Temperatura máxima"))
        self.mili.setText(_translate("MainWindow", "Temperatura mínima"))
        self.peod.setText(_translate("MainWindow", "Periodo señal referencia"))
        self.upax.setText(_translate("MainWindow", "Limite máximo superior"))
        self.upin.setText(_translate("MainWindow", "Limite minimo superior"))
        self.loax.setText(_translate("MainWindow", "Limite máximo inferior"))
        self.loin.setText(_translate("MainWindow", "Limite mínimo inferior"))
        self.alha.setText(_translate("MainWindow", "Valor Alfa"))
        self.maue.setText(_translate("MainWindow", "Valor máximo tolerable"))
        self.miue.setText(_translate("MainWindow", "Valor mínimo tolerable"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.LoadButton.setText(_translate("MainWindow", "Load"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.Modulation.setItemText(0, _translate("MainWindow", "Puro"))
        self.Modulation.setItemText(1, _translate("MainWindow", "Regresion"))
        self.Modulation.setItemText(2, _translate("MainWindow", "PID"))
        self.Modulation.setItemText(3, _translate("MainWindow", "Martinelli"))
        self.nuts.setText(_translate("MainWindow", "Número de experimentos"))
        self.suon.setText(_translate("MainWindow", "Succion"))
        self.ales.setText(_translate("MainWindow", "Número muestras aleatorias"))
        self.duon.setText(_translate("MainWindow", "Duracion del estimulo"))
        self.ines.setText(_translate("MainWindow", "Muestras iniciales"))
        self.tius.setText(_translate("MainWindow", "Tiempo entre estímulos"))
        self.nale.setText(_translate("MainWindow", "Nombre fichero"))
        self.naer.setText(_translate("MainWindow", "Nombre carpeta"))
        self.slep.setText(_translate("MainWindow", "Dormir"))
        self.vees.setText(_translate("MainWindow", "Vector de apertura de vávulas"))
        self.exon.setText(_translate("MainWindow", "Versión del experimento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))

