# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_plotwindow(object):
    def setupUi(self, plotwindow):
        plotwindow.setObjectName("plotwindow")
        plotwindow.resize(620, 447)
        self.checkBox = QtWidgets.QCheckBox(plotwindow)
        self.checkBox.setGeometry(QtCore.QRect(190, 620, 129, 21))
        self.checkBox.setObjectName("checkBox")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(plotwindow)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 260, 141, 61))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SFichero = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.SFichero.setObjectName("SFichero")
        self.verticalLayout_3.addWidget(self.SFichero)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(plotwindow)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 131, 231))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.VoltajecheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.VoltajecheckBox.setObjectName("VoltajecheckBox")
        self.verticalLayout_2.addWidget(self.VoltajecheckBox)
        self.ResistenciaCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.ResistenciaCheckBox.setObjectName("ResistenciaCheckBox")
        self.verticalLayout_2.addWidget(self.ResistenciaCheckBox)
        self.TemperaturacheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.TemperaturacheckBox.setObjectName("TemperaturacheckBox")
        self.verticalLayout_2.addWidget(self.TemperaturacheckBox)
        self.TemperaturaAcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.TemperaturaAcheckBox.setObjectName("TemperaturaAcheckBox")
        self.verticalLayout_2.addWidget(self.TemperaturaAcheckBox)
        self.HAmbientalcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.HAmbientalcheckBox.setObjectName("HAmbientalcheckBox")
        self.verticalLayout_2.addWidget(self.HAmbientalcheckBox)
        self.Texto = QtWidgets.QTextBrowser(plotwindow)
        self.Texto.setGeometry(QtCore.QRect(160, 20, 451, 301))
        self.Texto.setReadOnly(True)
        self.Texto.setObjectName("Texto")
        self.gridLayoutWidget = QtWidgets.QWidget(plotwindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 330, 211, 108))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.SSHPlotLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.SSHPlotLayout.setContentsMargins(0, 0, 0, 0)
        self.SSHPlotLayout.setObjectName("SSHPlotLayout")
        self.SSHFicheroLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.SSHFicheroLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.SSHFicheroLabel.setMouseTracking(True)
        self.SSHFicheroLabel.setAccessibleName("")
        self.SSHFicheroLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SSHFicheroLabel.setObjectName("SSHFicheroLabel")
        self.SSHPlotLayout.addWidget(self.SSHFicheroLabel, 0, 0, 1, 1)
        self.SSHFicheroEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.SSHFicheroEdit.setObjectName("SSHFicheroEdit")
        self.SSHPlotLayout.addWidget(self.SSHFicheroEdit, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 3, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.RefrescoLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.RefrescoLabel.setObjectName("RefrescoLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.RefrescoLabel)
        self.RefrescoEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.RefrescoEdit.setObjectName("RefrescoEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.RefrescoEdit)
        self.SSHPlotLayout.addLayout(self.formLayout, 2, 0, 1, 1)
        self.AnadirButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AnadirButton.setObjectName("AnadirButton")
        self.SSHPlotLayout.addWidget(self.AnadirButton, 3, 0, 1, 1)
        self.RepresentarButton = QtWidgets.QPushButton(plotwindow)
        self.RepresentarButton.setGeometry(QtCore.QRect(240, 410, 101, 31))
        self.RepresentarButton.setObjectName("RepresentarButton")
        self.SSHcheckBox = QtWidgets.QCheckBox(plotwindow)
        self.SSHcheckBox.setGeometry(QtCore.QRect(240, 330, 111, 21))
        self.SSHcheckBox.setObjectName("SSHcheckBox")

        self.retranslateUi(plotwindow)
        QtCore.QMetaObject.connectSlotsByName(plotwindow)

    def retranslateUi(self, plotwindow):
        _translate = QtCore.QCoreApplication.translate
        plotwindow.setWindowTitle(_translate("plotwindow", "Dialog"))
        self.checkBox.setText(_translate("plotwindow", "CheckBox"))
        self.SFichero.setText(_translate("plotwindow", "Seleccionar fichero"))
        self.VoltajecheckBox.setText(_translate("plotwindow", "Voltaje"))
        self.ResistenciaCheckBox.setText(_translate("plotwindow", "Resistencia"))
        self.TemperaturacheckBox.setText(_translate("plotwindow", "Temperatura"))
        self.TemperaturaAcheckBox.setText(_translate("plotwindow", "T. Ambiental"))
        self.HAmbientalcheckBox.setText(_translate("plotwindow", "H. Ambiental"))
        self.SSHFicheroLabel.setText(_translate("plotwindow", "Fichero SSH"))
        self.RefrescoLabel.setText(_translate("plotwindow", "Refresco(secs.)"))
        self.AnadirButton.setText(_translate("plotwindow", "Añadir fichero"))
        self.RepresentarButton.setText(_translate("plotwindow", "Representar"))
        self.SSHcheckBox.setText(_translate("plotwindow", "HabilitarSSH"))

